---
title: "pitfall_trapping_protocol_modified_from_v_sept2016"
output: md_document
---

# Arthropod Pitfall Trapping Protocol (Sept_2016)

*Overview:*

* Traps are set (opened) on day 1 and collected (closed) on day 4 quarterly. It does not matter in what order the pitfall sites are visited but the sites are grouped geographically.
* There are 10 traps at most sites—some sites have 11 installed in case a trap cannot be located (if more than 10 traps are found, set and collect only 10), and at NDV sites 12 traps are set and collected each time. Traps are usually ~5 meters apart on a straight line (except at residential sites and some commercial sites).
* Traps at non-agricultural sites consist of a piece of sewer pipe buried so it is flush with the ground. A 16-ounce plastic cup is placed in the pipe and traps are covered with a cut piece of sewer pipe lid when not in use (lids are spray painted green for traps located in lawns). At agricultural sites, there are no pipes in the ground.  For each visit, a fresh trap line is dug into the dirt.  
* For non-agricultural sites, take a few extra place-holding pipes into the field each time. Sometimes the pipes get dug out of the ground by animals or humans and need to be replaced.
* Do not set traps when it is raining, when heavy rain is expected, or when flood irrigation is in an agricultural field. If there is too much water in the cup to fit in the jar (from rain, crop irrigation, or landscape watering), a piece of plankton netting is used to filter out enough water to fit. After filtering the water, always rinse the netting into the jar with a wash bottle to collect any insects that may have stuck to it (even if you cannot see any insects).
* Scorpions are often encountered at the desert sites—take caution when removing the trap lids, when removing the cup from the ground (they are often found underneath the cup on the ground in the pipe), and when collecting the trap!!!
* A minimum of 7 traps must be collected on day 4, otherwise that location should be reset or disregarded for that collection cycle.  During a given collection cycle, a maximum of two ag sites can be disregarded if the collection is not successful (due to irrigation, tilling, or whatever).

*Field Procedure:*

**Day 1: Setting the traps:**

* Remove the lid from the trap and ensure the plastic cup is clean and free of any debris or dead insects. If the cup is missing, very dirty, or damaged, replace with a new one.
* Collect the trap lids and bring back to the lab until traps are collected on day 4. Take note if any lids are missing to ensure there is a lid for each trap when you return to close the traps on day 4. At some of the more remote desert sites, the lids can be left next to the trap with rocks piled on top instead of bringing back to the lab.
* At ag sites, dig a fresh trap line into the dirt and use TWO cups, one to hold the place and the other inside it to collect the arthropods. Ag site traps are placed lengthwise along the toe of one berm, not on the crest of berms, or across the crop spaces between berms. This is done to minimize the likelihood of the cups filling with water if the field gets irrigated, but still capture arthropods that inhabit the crop area. 

**Before collecting:**

* Fill sample jars ~halfway with a diluted ethanol solution. Ethanol can be obtained from Lab Stores with an alcohol release form. The solution is prepared in GWC 681 in gallon jugs with 70% ethanol, 30% water.  

**Day 4: Collecting:**

* If lizards are found in the cup, release them and note their presence on the data sheet.
* Pour the ethanol solution in the cup and swirl. Pour the contents of the cup into the jar and insert the appropriate jar label (labels could also be inserted while filling the jars).
* Replace the lid (green for grass, white otherwise), piling rocks on top of the lids in desert areas to help keep the lids on until the next collection cycle. At ag sites, remove the cups and bring back to the lab.
* Enter appropriate information for each site on the field data sheet (including type of crop at ag sites) and return with the specimen jars to the entomology laboratory at ASU (LSA 302).

*Laboratory procedure:*

* Organisms are sorted to the lowest practical taxonomic unit, and enumerated.
* Organism taxonomy and number are entered into the CAP LTER arthropod database along with appropriate sampling information and other relevant details.